server:
  port: 8080
  display-name: shudu

spring:
  profiles:
    active: dev
  # mvc配置
  mvc:
    view:
      prefix: /pages/
      suffix: .html
  # jpa
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          show_sql: true
          use_sql_comments: true
          format_sql: true
  # dataSource配置
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    # url: jdbc:h2:file:./db/dbInfo
    username: root
    password: test
  # 数据库初始化配置
  sql:
    init:
      platform: h2
      # 项目启动后自动执行的DDL语句
      schema-locations: classpath:db/schema.sql
      # 项目启动后自动执行的DML语句
      data-locations: classpath:db/data.sql
  # h2配置, 默认控制台url:http://127.0.0.1:8080/h2-console/
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true

logging:
  level:
    org.hibernate.type.descriptor.sql.BasicBinder: trace
